export interface JobQuery {
  query: string;
  location: string;
  tier: 1 | 2;
}

const TIER1_ROLES = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Frontend Developer",
  "Frontend Engineer",
  "Backend Engineer",
  "Backend Developer",
  "Full Stack Developer",
  "Full Stack Engineer",
  "React Developer",
  "Node.js Developer",
  "Python Developer",
  "Java Developer",
  "Go Developer",
  "Rust Developer",
  "TypeScript Developer",
  "iOS Developer",
  "Android Developer",
  "Mobile Developer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Cloud Engineer",
  "Infrastructure Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "ML Ops Engineer",
  "Data Analyst",
  "QA Engineer",
  "SDET",
  "Test Engineer",
  "Security Engineer",
  "Cybersecurity Analyst",
  "Cloud Architect",
  "Solutions Architect",
  "Engineering Manager",
  "VP of Engineering",
  "CTO",
  "Technical Lead",
  "Principal Engineer",
  "Product Manager",
  "Senior Product Manager",
  "Technical Product Manager",
  "Product Owner",
  "UX Designer",
  "UI Designer",
  "Product Designer",
  "UX Researcher",
  "Interaction Designer",
  "Design Manager",
  "Technical Writer",
  "Developer Advocate",
  "Developer Relations",
  "Scrum Master",
  "Agile Coach",
  "IT Manager",
  "Systems Administrator",
  "Network Engineer",
  "Database Administrator",
  "Blockchain Developer",
  "Embedded Software Engineer",
  "Firmware Engineer",
  "Game Developer",
  "Graphics Engineer",
];

const TIER2_ROLES = [
  "Marketing Manager",
  "Digital Marketing Manager",
  "Content Marketing Manager",
  "SEO Specialist",
  "Growth Manager",
  "Performance Marketing",
  "Brand Manager",
  "Social Media Manager",
  "Email Marketing Specialist",
  "Marketing Analyst",
  "CMO",
  "Sales Representative",
  "Account Executive",
  "Business Development Representative",
  "Sales Manager",
  "Enterprise Sales",
  "Sales Engineer",
  "Sales Director",
  "VP of Sales",
  "Customer Success Manager",
  "Account Manager",
  "Client Services Manager",
  "Customer Support Manager",
  "Operations Manager",
  "Operations Analyst",
  "Chief Operating Officer",
  "Business Operations",
  "Strategy Consultant",
  "Management Consultant",
  "Business Analyst",
  "Financial Analyst",
  "Investment Analyst",
  "Equity Research Analyst",
  "Risk Analyst",
  "Quantitative Analyst",
  "Accountant",
  "Senior Accountant",
  "CPA",
  "Tax Analyst",
  "Auditor",
  "Controller",
  "CFO",
  "Financial Planner",
  "Bookkeeper",
  "Actuary",
  "HR Manager",
  "HR Business Partner",
  "Recruiter",
  "Technical Recruiter",
  "Talent Acquisition",
  "People Operations",
  "Compensation Analyst",
  "Benefits Specialist",
  "CHRO",
  "Project Manager",
  "Program Manager",
  "Portfolio Manager",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Procurement Specialist",
  "Warehouse Manager",
  "Inventory Manager",
  "Purchasing Manager",
  "Nurse",
  "Registered Nurse",
  "Nurse Practitioner",
  "Physician",
  "Physician Assistant",
  "Medical Assistant",
  "Pharmacist",
  "Physical Therapist",
  "Occupational Therapist",
  "Dental Hygienist",
  "Healthcare Administrator",
  "Clinical Research Associate",
  "Medical Coder",
  "Health Information Technician",
  "Lawyer",
  "Attorney",
  "Paralegal",
  "Legal Assistant",
  "Compliance Officer",
  "Regulatory Affairs",
  "Contract Manager",
  "General Counsel",
  "Patent Attorney",
  "Teacher",
  "Professor",
  "Instructional Designer",
  "Curriculum Developer",
  "School Administrator",
  "Academic Advisor",
  "Tutor",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Chemical Engineer",
  "Structural Engineer",
  "Environmental Engineer",
  "Industrial Engineer",
  "Aerospace Engineer",
  "Biomedical Engineer",
  "Manufacturing Engineer",
  "Process Engineer",
  "Materials Engineer",
  "Graphic Designer",
  "Art Director",
  "Creative Director",
  "Motion Designer",
  "Video Editor",
  "Photographer",
  "Copywriter",
  "Content Writer",
  "Editor",
  "Journalist",
  "Public Relations Specialist",
  "Communications Manager",
  "Real Estate Agent",
  "Property Manager",
  "Mortgage Loan Officer",
  "Appraiser",
  "Construction Manager",
  "General Contractor",
  "Architect",
  "Interior Designer",
  "Urban Planner",
  "Executive Assistant",
  "Administrative Assistant",
  "Office Manager",
  "Receptionist",
  "Data Entry Clerk",
  "Insurance Agent",
  "Claims Adjuster",
  "Underwriter",
  "Actuary",
  "Restaurant Manager",
  "Chef",
  "Bartender",
  "Hotel Manager",
  "Event Planner",
  "Travel Agent",
  "Flight Attendant",
  "Truck Driver",
  "Delivery Driver",
  "Warehouse Associate",
  "Electrician",
  "Plumber",
  "HVAC Technician",
  "Welder",
  "Machinist",
  "Automotive Technician",
];

const LOCATIONS = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "San Francisco, CA",
  "Columbus, OH",
  "Charlotte, NC",
  "Indianapolis, IN",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Nashville, TN",
  "Oklahoma City, OK",
  "Portland, OR",
  "Las Vegas, NV",
  "Memphis, TN",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Atlanta, GA",
  "Miami, FL",
  "Raleigh, NC",
  "Minneapolis, MN",
  "Tampa, FL",
  "Boston, MA",
  "Detroit, MI",
  "Salt Lake City, UT",
  "Pittsburgh, PA",
  "Cincinnati, OH",
  "Kansas City, MO",
  "Sacramento, CA",
  "Orlando, FL",
  "Cleveland, OH",
  "St. Louis, MO",
  "Richmond, VA",
  "Boise, ID",
  "Remote",
];

function buildMatrix(): JobQuery[] {
  const queries: JobQuery[] = [];
  const seen = new Set<string>();

  const add = (role: string, loc: string, tier: 1 | 2) => {
    const key = `${role}|${loc}`;
    if (seen.has(key)) return;
    seen.add(key);
    queries.push({ query: role, location: loc, tier });
  };

  // Tier 1: every tech role x every location + Remote
  for (const role of TIER1_ROLES) {
    add(role, "Remote", 1);
    for (const loc of LOCATIONS) {
      add(role, loc, 1);
    }
  }

  // Tier 2: every other role x top 15 metros + Remote
  const topLocations = LOCATIONS.slice(0, 15);
  topLocations.push("Remote");
  for (const role of TIER2_ROLES) {
    for (const loc of topLocations) {
      add(role, loc, 2);
    }
  }

  return queries;
}

export const JOB_QUERIES = buildMatrix();

export const TIER1_QUERIES = JOB_QUERIES.filter((q) => q.tier === 1);
export const TIER2_QUERIES = JOB_QUERIES.filter((q) => q.tier === 2);

export const TOTAL_QUERIES = JOB_QUERIES.length;
